#1 [Feat] add signin, signup, signout
OssPipeline/REGO pull request #2
Opened 2022-12-04 09:29 UTC by plum-king

2022-12-13 12:59 UTC, zzhxxnee commented
main.js 의 8번 라인 console.log 는 삭제하는 것이 좋을 것 같습니다.

2022-12-14 09:14 UTC, plum-king commented
확인했습니다.

2022-12-14 09:19 UTC, leejw-lu requested changes
확인했습니다. 지현님이 말하신 부분만 수정하면 될 것 같아요.

2022-12-14 09:31 UTC, merged

2022-12-14 13:05 UTC, plum-king reviewed
말씀하신 대로 수정했습니다!